# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0006_auto_20170821_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.StatusCheck')),
                ('host', models.TextField(help_text=b'Host to check.', null=True)),
                ('port', models.PositiveIntegerField(help_text=b'Port to check.', null=True)),
                ('helo_address', models.TextField(help_text=b'Advertised client address.', null=True)),
                ('sender', models.EmailField(help_text=b'Address to test sending as.', null=True)),
                ('recipient', models.EmailField(help_text=b'Address to test sending to.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.statuscheck',),
        ),
    ]
